// Mocks generated by Mockito 5.4.5 from annotations
// in land_asset_valuation/test/application/pages/conditionReport/cubit/condition_report_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dartz/dartz.dart' as _i3;
import 'package:land_asset_valuation/application/core/error/failures.dart'
    as _i9;
import 'package:land_asset_valuation/data/datasource/shared_preference.dart'
    as _i11;
import 'package:land_asset_valuation/data/models/condition_report_model.dart'
    as _i10;
import 'package:land_asset_valuation/data/models/master_data_model.dart' as _i6;
import 'package:land_asset_valuation/data/services/condition_report_sync_service.dart'
    as _i15;
import 'package:land_asset_valuation/data/services/connectivity_service.dart'
    as _i14;
import 'package:land_asset_valuation/domain/repositories/condition_report_repository.dart'
    as _i2;
import 'package:land_asset_valuation/domain/repositories/master_data_repository.dart'
    as _i5;
import 'package:land_asset_valuation/domain/usecases/get_master_data_usecase.dart'
    as _i13;
import 'package:land_asset_valuation/domain/usecases/send_condition_report_usecase.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:shared_preferences/shared_preferences.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeConditionReportRepository_0 extends _i1.SmartFake
    implements _i2.ConditionReportRepository {
  _FakeConditionReportRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPreferences_2 extends _i1.SmartFake
    implements _i4.SharedPreferences {
  _FakeSharedPreferences_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMasterDataRepository_3 extends _i1.SmartFake
    implements _i5.MasterDataRepository {
  _FakeMasterDataRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMasterDataResponse_4 extends _i1.SmartFake
    implements _i6.MasterDataResponse {
  _FakeMasterDataResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SendConditionReportUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendConditionReportUseCase extends _i1.Mock
    implements _i7.SendConditionReportUseCase {
  MockSendConditionReportUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ConditionReportRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeConditionReportRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ConditionReportRepository);

  @override
  _i8.Future<_i3.Either<_i9.Failure, bool>> call(
    _i10.ConditionReportModel? report,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [report]),
            returnValue: _i8.Future<_i3.Either<_i9.Failure, bool>>.value(
              _FakeEither_1<_i9.Failure, bool>(
                this,
                Invocation.method(#call, [report]),
              ),
            ),
          )
          as _i8.Future<_i3.Either<_i9.Failure, bool>>);
}

/// A class which mocks [AppSharedData].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppSharedData extends _i1.Mock implements _i11.AppSharedData {
  MockAppSharedData() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.SharedPreferences get secureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#secureStorage),
            returnValue: _FakeSharedPreferences_2(
              this,
              Invocation.getter(#secureStorage),
            ),
          )
          as _i4.SharedPreferences);

  @override
  set secureStorage(_i4.SharedPreferences? _secureStorage) =>
      super.noSuchMethod(
        Invocation.setter(#secureStorage, _secureStorage),
        returnValueForMissingStub: null,
      );

  @override
  dynamic setData(String? key, String? value) =>
      super.noSuchMethod(Invocation.method(#setData, [key, value]));

  @override
  String getData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [key]),
            returnValue: _i12.dummyValue<String>(
              this,
              Invocation.method(#getData, [key]),
            ),
          )
          as String);

  @override
  bool hasData(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#hasData, [key]),
            returnValue: false,
          )
          as bool);

  @override
  dynamic clearData(String? key) =>
      super.noSuchMethod(Invocation.method(#clearData, [key]));

  @override
  dynamic setDataBool(String? key, bool? value) =>
      super.noSuchMethod(Invocation.method(#setDataBool, [key, value]));

  @override
  bool getDataBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDataBool, [key]),
            returnValue: false,
          )
          as bool);
}

/// A class which mocks [GetMasterDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMasterDataUseCase extends _i1.Mock
    implements _i13.GetMasterDataUseCase {
  MockGetMasterDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.MasterDataRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMasterDataRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.MasterDataRepository);

  @override
  _i8.Future<_i6.MasterDataResponse> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i8.Future<_i6.MasterDataResponse>.value(
              _FakeMasterDataResponse_4(this, Invocation.method(#call, [])),
            ),
          )
          as _i8.Future<_i6.MasterDataResponse>);
}

/// A class which mocks [ConditionReportRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConditionReportRepository extends _i1.Mock
    implements _i2.ConditionReportRepository {
  MockConditionReportRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.Either<_i9.Failure, bool>> sendConditionReport(
    _i10.ConditionReportModel? report,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendConditionReport, [report]),
            returnValue: _i8.Future<_i3.Either<_i9.Failure, bool>>.value(
              _FakeEither_1<_i9.Failure, bool>(
                this,
                Invocation.method(#sendConditionReport, [report]),
              ),
            ),
          )
          as _i8.Future<_i3.Either<_i9.Failure, bool>>);

  @override
  _i8.Future<int> getPendingReportsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingReportsCount, []),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<_i10.ConditionReportModel>> getPendingReports() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingReports, []),
            returnValue: _i8.Future<List<_i10.ConditionReportModel>>.value(
              <_i10.ConditionReportModel>[],
            ),
          )
          as _i8.Future<List<_i10.ConditionReportModel>>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i14.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i8.Stream<bool>.empty(),
          )
          as _i8.Stream<bool>);

  @override
  _i8.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConditionReportSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConditionReportSyncService extends _i1.Mock
    implements _i15.ConditionReportSyncService {
  MockConditionReportSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i15.SyncStatus> get syncStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#syncStatusStream),
            returnValue: _i8.Stream<_i15.SyncStatus>.empty(),
          )
          as _i8.Stream<_i15.SyncStatus>);

  @override
  void initialize() => super.noSuchMethod(
    Invocation.method(#initialize, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> syncPendingReports() =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingReports, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<int> getPendingReportsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingReportsCount, []),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<void> retryFailedReports() =>
      (super.noSuchMethod(
            Invocation.method(#retryFailedReports, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
