import 'package:flutter/material.dart';
import 'package:land_asset_valuation/application/core/utils/app_colors/light_color_list.dart';
import 'package:land_asset_valuation/application/core/utils/app_colors/theme_data.dart';
import 'package:land_asset_valuation/application/core/utils/app_styling.dart';
import 'package:land_asset_valuation/application/core/widgets/custom_button.dart';
import 'package:signature/signature.dart';
import 'dart:typed_data';
import 'dart:convert';

/// A widget that lets the user draw a signature and submit or clear it.
class SignatureBox extends StatefulWidget {
  final String title;
  // Callback function to send signature as Uint8List when changed
  final Function(Uint8List?)? onSignatureChanged;

  const SignatureBox({
    super.key,
    required this.title,
    this.onSignatureChanged,
  });

  @override
  State<SignatureBox> createState() => _SignatureBoxState();
}

class _SignatureBoxState extends State<SignatureBox> {
  // Controller to manage the drawn signature
  late final SignatureController _controller;

  @override
  void initState() {
    super.initState();
    // Initialize the SignatureController with drawing parameters
    _controller = SignatureController(
      penStrokeWidth: 2,
      penColor: Colors.black,
      exportBackgroundColor: Colors.white,
    );

    // Listen to changes in the signature box and call the handler
    _controller.addListener(_handleSignatureChange);
  }

  // Handler that is triggered whenever the signature is updated.
  Future<void> _handleSignatureChange() async {
    // Ensure the widget is still mounted
    if (!mounted) return;
    
    // Only process if there is content in the signature and a callback is provided
    if (_controller.isNotEmpty && widget.onSignatureChanged != null) {
      try {
        // Convert the drawn signature to PNG byte data
        final signature = await _controller.toPngBytes();
        // Invoke the callback with the generated bytes
        widget.onSignatureChanged!(signature);
      } catch (e) {
        // Log error if any conversion issue occurs and pass null
        debugPrint('Error converting signature to PNG: $e');
        widget.onSignatureChanged!(null);
      }
    }
  }

  // Handler for the submit button.
  // Converts the signature to a Base64 string and logs it.
  Future<void> _handleSubmit() async {
    // Do nothing if the signature box is empty
    if (_controller.isEmpty) {
      debugPrint('No signature to submit');
      return;
    }

    try {
      // Convert the signature to PNG byte data
      final signature = await _controller.toPngBytes();
      if (signature != null) {
        // Encode the signature bytes to a Base64 string
        final base64String = base64Encode(signature);
        debugPrint('Submitted Signature as Base64: $base64String');
      }
    } catch (e) {
      // Log any errors during conversion
      debugPrint('Error converting signature to base64: $e');
    }
  }

  // Handler for the clear button.
  // Clears the signature and notifies via callback.
  void _handleClear() {
    _controller.clear();
    widget.onSignatureChanged?.call(null);
  }

  @override
  void dispose() {
    // Remove listener and release controller resources
    _controller.removeListener(_handleSignatureChange);
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      mainAxisSize: MainAxisSize.min,
      children: [
        // Display the box title
        Text(
          widget.title,
          style: AppStyling.normalTextSize14.copyWith(
            color: colors(context).colorGrey6,
          ),
        ),
        const SizedBox(height: 8),
        // Container that holds the drawing area
        Container(
          width: 496,
          height: 150,
          decoration: BoxDecoration(
            border: Border.all(
              color: colors(context).colorPrimary5 ?? LightColorList.lightPrimary700,
              width: 1,
            ),
            borderRadius: BorderRadius.circular(10),
          ),
          child: ClipRRect(
            borderRadius: BorderRadius.circular(10),
            // Signature widget provides a drawing canvas
            child: Signature(
              controller: _controller,
              backgroundColor: colors(context).colorWhite ?? LightColorList.lightColorWhite,
            ),
          ),
        ),
        const SizedBox(height: 8),
        // Row containing Clear and Submit buttons
        SizedBox(
          width: 496,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: [
              // Button to clear the signature area
              CustomButton(
                text: 'Clear',
                onPressed: _handleClear,
                backgroundColor: colors(context).colorGrey1 ?? LightColorList.lightGrey50,
              ),
              const SizedBox(width: 8),
              // Button to submit the current signature
              CustomButton(
                text: 'Submit',
                onPressed: _handleSubmit,
                backgroundColor: colors(context).colorPrimary5 ?? LightColorList.lightPrimary700,
              ),
            ],
          ),
        ),
      ],
    );
  }
}